---
title: "Biodiversité en chiffre"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: paper
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(spdplyr)
library(ggplot2)
library(plotly)
library(readxl)
library(tidyr)
library(knitr)
library(leaflet)
library(arules)
library(sf)
library(RColorBrewer)
library(rgdal)
library(MazamaSpatialUtils)
file = "C:/Users/demare.g/OneDrive - ORU OCCITANIE/uicn.xlsx"
#UNCI
unci = read_xlsx(file, sheet = "UNCI Red list")
estimed = read_xlsx(file, sheet = "UNCI Red list evaluated")
threated = read_xlsx(file, sheet = "Threatened species country")
#pays
paysNom = read_xlsx("C:/Users/demare.g/OneDrive - ORU OCCITANIE/pays names.xlsx", sheet = "Feuil1") 
# geolocalisation
monde = readOGR("C:/Users/demare.g/OneDrive - ORU OCCITANIE/countries.geojson", stringsAsFactors = F,encoding = 'UTF-8')
```

Presentation {data-navmenu="Menu"}
=====================================

Column {data-width=400}
-----------------------------------------------------------------------

### Informations Utiles

__Les sources__

Les données présentées sont issues de rapports publiés par l'Internation Union for the Natural Conservation (IUNC).
Les chiffres 

Source : [Number of threatened species](nc.iucnredlist.org/redlist/content/attachment_files/2019_2_RL_Table_1b.pdf)

__Biodiversité__

C'est la diversité des écosystèmes, des espèces et des gènes dans l'espace et dans le temps, ainsi que les interactions au sein de ces niveaux d'organisation et entre eux.

__La Red List des espèces menacés__

La red list est une échelle qui évaluent les risques de disparitions des êtres vivants. Ils sont classés sur une échelle de 8 niveaux en fonction de la valeur d'un indicateur est calculé avec les critères suivants :

* Espèces.
* Taille de la population.
* Aire de répartition géographique.
* Degré de peuplement.
* Fragementation de la répartition géographique.

Depuis 1, 754 espèces se sont éteintes.

Column {data-width=600}
-----------------------------------------------------------------------

### Evolution du nombre d'espèces étudiées et menacees

```{r}
time = unci %>% 
  group_by(year) %>%
  summarise(described = sum(described, na.rm = T), threated = sum(threated, na.rm = T)) %>%
ggplot() +
  geom_area(aes(x = year, y = described), fill = "#9de17b") +
  geom_line(aes(x = year, y = described), color = "#8ecb6e") +
  geom_point(aes(x = year, y = described), color = "#8ecb6e") +
  geom_area(aes(x = year, y = threated), fill = "#ffccd6") +
  geom_line(aes(x = year, y = threated), color = "#feb0bf") +
  geom_point(aes(x = year, y = threated), color = "#feb0bf") +
  theme_minimal() 
ggplotly(time)
```


### Espèces menacées par catégorie


```{r}
organisms = unci %>%
  filter(year == 2019) %>%
  mutate( organisms = substr(organisms, 1, 16) ) %>%
  group_by(organisms) %>%
  summarise(described = sum(described)-sum(threated), threated = sum(threated)) %>%
  gather( key = "evalued", value = "species", 2:3) %>%
  ggplot( aes( x = organisms, y = species, fill = evalued))  +
  coord_flip() +
  geom_col() +
  scale_fill_manual( values = c("#8ecb6e", "#feb0bf") )+
  theme_minimal() +
  xlab("")
ggplotly(organisms)
```

### Le types d'espèces vertébrés


```{r}
vertebrates = unci %>%
  filter(year == 2019 & toupper(organisms) == "VERTEBRATES") %>%
  mutate(described = described-threated) %>%
  gather( key = "evalued", value = "speciesNb", 5:6) %>%
  ggplot( aes( x = reorder(species, speciesNb), y = speciesNb, fill = evalued))  +
  coord_flip() +
  geom_col() +
  scale_fill_manual( values = c("#8ecb6e", "#feb0bf") )+
  theme_minimal() +
  xlab("")
ggplotly(vertebrates)
```

Par pays {data-navmenu="Menu"}
=====================================

### Nombre d espèces menacées par pays

```{r}
pays = monde %>%
  left_join(paysNom, by = c('ADMIN' = 'country1')) %>%
  left_join(threated, by = c('country2' = 'country'))
pays = simplify(pays)

couches = colnames(pays@data[,9:ncol(pays@data)])
cartes = leaflet(pays) %>%
  setView(lng = 7, lat = 45, zoom = 5) %>%
  addLayersControl( baseGroups = couches, options = layersControlOptions(collapsed = FALSE))

for( i in couches ){
  nb = pays@data[,i]
  discret = discretize(nb, method = "cluster", )
  couleurs = discret
  levels(couleurs) = brewer.pal(length(levels(discret)), "YlOrRd")
  assign(i, data.frame(
                  nbre = nb,
                  discret = discret,
                  couleurs = couleurs
                  ))
  assign(paste("label",i,sep=""), sprintf( paste("<strong>%s</strong><br/>", i, "=", '%g'),  pays$ADMIN, nb ) %>% lapply(htmltools::HTML))
  cartes = cartes %>%
    addPolygons(
      fillColor = get(i)$couleurs, weight = 1, color = "white", fillOpacity = 0.6, label =  get(paste("label",i,sep="")),
      highlightOptions = highlightOptions(color = "white", weight = 2, bringToFront = TRUE),
      labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"), textsize = "15px", direction = "auto"), group = i
    )
}
cartes
```